### ISSUE TITLE
New to this not sure where Im going wrong

### ISSUE THREAD

**Issue by davelaaa** [UnMars/Prolific-Joiner#16]
C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Getting a new bearer token...
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    p_updater = ProlificUpdater()
  File "main.py", line 28, in __init__
    else: self.bearer = "Bearer " + self.get_bearer_token()
  File "main.py", line 76, in get_bearer_token
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options= options)
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\webdriver_manager\core\manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\webdriver_manager\core\download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\webdriver_manager\core\http.py", line 33, in get
    self.validate_response(resp)
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/119.0.6045/chromedriver_win32.zip

is there an easy fix?

**Comment by ndrefg** [comment]
Hello, did you try this commands?

```
pip install webdriver_manager --upgrade 
pip install selenium --upgrade
```
