### ISSUE TITLE
ModuleNotFoundError: No module named 'blinker._saferef'

### ISSUE THREAD

**Issue by steffmeisteren** [UnMars/Prolific-Joiner#22]
Hey, I'm pretty noob in regards to python. When trying to run the script, I get this:

C:\Users\Admin\Desktop\Prolific-Joiner-main>python main.py
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Prolific-Joiner-main\main.py", line 1, in <module>
    from seleniumwire import webdriver
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'

How do I fix this? Thanks!

**Comment by n0rmal900** [comment]
run `pip install blinker==1.7.0` should should

**Comment by steffmeisteren** [comment]
> run `pip install blinker==1.7.0` should help

Thanks, it worked!

However, now I'm met with "C:\Users\Admin\Desktop\Prolific-Joiner-main>py main.py
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Prolific-Joiner-main\main.py", line 14, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'"

Any advice?

**Comment by n0rmal900** [comment]
DId you read readme? You need to install requirements `pip install -r requirements.txt` however one of modules needs update, so after that `python3 -m pip install webdriver-manager --upgrade
`
