### ISSUE TITLE
Error for getting requirements

### ISSUE THREAD

**Issue by Arslan30** [UnMars/Prolific-Joiner#26]
When trying 

pip install -r requirements.txt

Following error occurs:

'Collecting playsound>=1.3.0 (from -r requirements.txt (line 1))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\<>\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\<>\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\<>\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\<>\AppData\Local\Temp\pip-build-env-9on9mwu8\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\<>\AppData\Local\Temp\pip-build-env-9on9mwu8\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\<>\AppData\Local\Temp\pip-build-env-9on9mwu8\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\<>\AppData\Local\Temp\pip-build-env-9on9mwu8\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Users\<>\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1147, in getsource
          lines, lnum = getsourcelines(object)
        File "C:\Users\<>\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1129, in getsourcelines
          lines, lnum = findsource(object)
        File "C:\Users\<>\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 958, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.'

**Comment by Arslan30** [comment]
accidently completed
