### ISSUE TITLE
Help getting the log in to work? 

### ISSUE THREAD

**Issue by SAitken91** [UnMars/Prolific-Joiner#27]
It times out every time with this message? 
[+] Getting a new bearer token...

DevTools listening on ws://127.0.0.1:57084/devtools/browser/41031c28-374c-4f3b-b092-28580758ad05
Driver started
Login in...
Traceback (most recent call last):
  File "C:\Users\\OneDrive\Desktop\New folder\Prolific-Joiner\Prolific-Joiner\main.py", line 210, in <module>
    p_updater = ProlificUpdater()
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\\OneDrive\Desktop\New folder\Prolific-Joiner\Prolific-Joiner\main.py", line 33, in __init__
    self.bearer = "Bearer " + self.get_bearer_token()
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\OneDrive\Desktop\New folder\Prolific-Joiner\Prolific-Joiner\main.py", line 109, in get_bearer_token
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "image-container")))
  File "C:\Users\\OneDrive\Desktop\New folder\Prolific-Joiner\Prolific-Joiner\venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x0085B8E3+45827]
        (No symbol) [0x007EDCC4]
        (No symbol) [0x006E150F]
        (No symbol) [0x007220BC]
        (No symbol) [0x0072216B]
        (No symbol) [0x0075E0F2]
        (No symbol) [0x00742E44]
        (No symbol) [0x0075C034]
        (No symbol) [0x00742B96]
        (No symbol) [0x00716998]
        (No symbol) [0x0071751D]
        GetHandleVerifier [0x00B14513+2899763]
        GetHandleVerifier [0x00B6793D+3240797]
        GetHandleVerifier [0x008E13B4+593364]
        GetHandleVerifier [0x008E82DC+621820]
        (No symbol) [0x007F70A4]
        (No symbol) [0x007F37A8]
        (No symbol) [0x007F3947]
        (No symbol) [0x007E59FE]
        BaseThreadInitThunk [0x76897BA9+25]
        RtlInitializeExceptionChain [0x77D2C10B+107]
        RtlClearBits [0x77D2C08F+191]
        

losing my wits trying to get this to work

**Comment by SAitken91** [comment]
reinstalled now I'm having this error:

selenium.common.exceptions.WebDriverException: Message: chrome not reachable
Stacktrace:
        GetHandleVerifier [0x0097B8E3+45827]
        (No symbol) [0x0090DCC4]
        (No symbol) [0x0080138D]
        (No symbol) [0x007EFCEC]
        (No symbol) [0x00833202]
        (No symbol) [0x0082E400]
        (No symbol) [0x0082A339]
        (No symbol) [0x0086C9A2]
        (No symbol) [0x0086C1CA]
        (No symbol) [0x00862B96]
        (No symbol) [0x00836998]
        (No symbol) [0x0083751D]
        GetHandleVerifier [0x00C34513+2899763]
        GetHandleVerifier [0x00C8793D+3240797]
        GetHandleVerifier [0x00A013B4+593364]
        GetHandleVerifier [0x00A082DC+621820]
        (No symbol) [0x009170A4]
        (No symbol) [0x009137A8]
        (No symbol) [0x00913947]
        (No symbol) [0x009059FE]
        BaseThreadInitThunk [0x76897BA9+25]
        RtlInitializeExceptionChain [0x77D2C10B+107]
        RtlClearBits [0x77D2C08F+191]

**Comment by noekun11** [comment]
hey, i got the same error, Maybe you should try reading "readme.md" and follow the "configuration part(editing the config.json) " and the error should just go away... Thank me later..
