### ISSUE TITLE
script doesnt work after 1-2 months of working

### ISSUE THREAD

**Issue by Daiiku** [UnMars/Prolific-Joiner#8]
Title explains, error's are listed below. After a while the script fails to work, no clue how. Got this 1-2 months ago after using the script 1-2 months. I run a slightly modified version of the code that uses a telegram api to send me messages on my phone, but it also fails to work with the main release of the code with the same error. Last time to fix the issue I have no clue what I did but it worked again. If anyone knows please let me know.

Getting a new bearer token...
Traceback (most recent call last):
  File "C:\Users\Thomm\Downloads\prolific\main.py", line 154, in <module>
    p_updater = ProlificUpdater()
  File "C:\Users\Thomm\Downloads\prolific\main.py", line 30, in __init__
    self.bearer = "Bearer " + self.get_bearer_token()
  File "C:\Users\Thomm\Downloads\prolific\main.py", line 77, in get_bearer_token
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager(version="114.0.5735.16").install()), options= options)
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Thomm\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00B46E73+48323]
	(No symbol) [0x00AD9661]
	(No symbol) [0x009E5308]
	(No symbol) [0x00A0634C]
	(No symbol) [0x00A02093]
	(No symbol) [0x00A00719]
	(No symbol) [0x00A30DF5]
	(No symbol) [0x00A30ADC]
	(No symbol) [0x00A2A6D6]
	(No symbol) [0x00A0847C]
	(No symbol) [0x00A0957D]
	GetHandleVerifier [0x00DAFD5D+2575277]
	GetHandleVerifier [0x00DEF86E+2836158]
	GetHandleVerifier [0x00DE96DC+2811180]
	GetHandleVerifier [0x00BD41B0+626688]
	(No symbol) [0x00AE314C]
	(No symbol) [0x00ADF4B8]
	(No symbol) [0x00ADF59B]
	(No symbol) [0x00AD21B7]
	BaseThreadInitThunk [0x76CA7D59+25]
	RtlInitializeExceptionChain [0x77E8B79B+107]
	RtlClearBits [0x77E8B71F+191]

**Comment by usdbrl** [comment]
It happens to me yesterday, ater my Chrome browser updating. There's a line on the script that sets a specific version of Chrome for the script to work, if you change the version to a "blank" one, then the script runs on all versions.

The original line:
driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager(version="114.0.5735.16").install()), options= options)

All versions modification:
driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options= options)

I hope it works for you the same way it did for me!

**Comment by UnMars** [comment]
> It happens to me yesterday, ater my Chrome browser updating. There's a line on the script that sets a specific version of Chrome for the script to work, if you change the version to a "blank" one, then the script runs on all versions.
> 
> 
> 
> The original line:
> 
> `driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager(version="114.0.5735.16").install()), options= options)`
> 
> 
> 
> All versions modification:
> 
> `driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options= options)`
> 
> 
> 
> I hope it works for you the same way it did for me!

Fixed in the latest commit. Thanks a lot ! (I must had forget to remove the version specific chromedriver I used to test the script :p)
